dump__bash_var() {
	local prefix=$1

	printf "# generated by dump__bash_var %q\n" "$prefix"
	for var_name in $(eval "echo \"\${!${prefix}@}\""); do
		printf '%s=%q\n' "$var_name" "${!var_name}"
	done
	echo
}

dump__bash_var_export() {
	local prefix=$1

	printf "# generated by dump__bash_var_export %q\n" "$prefix"
	for var_name in $(eval "echo \"\${!${prefix}@}\""); do
		printf 'export %s=%q\n' "$var_name" "${!var_name}"
	done
	echo
}

dump__bash_func() {
	local prefix=$1

	printf "# generated by dump__bash_func %q\n" "$prefix"
	for func_name in $(declare -F | cut -d ' ' -f 3); do
		if [[ "$func_name" == "$prefix"* ]]; then
			declare -f "$func_name"
		fi
	done
	echo
}

dump__verbose() {
	local prefix=$1

	local need_newline=0
	for var_name in $(eval "echo \"\${!${prefix}@}\""); do
		printf "$color__red%s$color__reset=$color__green%q$color__reset\n" "$var_name" "${!var_name}"
		need_newline=1
	done
	if [[ $need_newline -eq 1 ]]; then
		echo
	fi
}
