real__dump() {
	echo "# generated by real__dump"
	for var_name in "${!REAL_@}"; do
		printf '%s=%q\n' "$var_name" "${!var_name}"
	done
	echo
}

real__bash() {
	if [ -n "${REAL_HOST}" ]; then
		ssh -T "$REAL_HOST" -l "$REAL_LOGIN" bash
	else
		bash
	fi
}

real__rsync() {
	local src=$1; shift
	local dest=$1; shift

	if [ -n "${REAL_HOST}" ]; then
		rsync -e ssh "$@" "$src" "$REAL_HOST:$dest"
	else
		rsync "$@" "$src" "$dest"
	fi	
}

real__init() {
	: ${REAL_HOST:=}
	: ${REAL_LOGIN:=$(whoami)}

	if [[ "${REAL_ROOT:-}" == "" ]]; then
		eval "$(echo "printf 'REAL_ROOT=%q\n' \$HOME" | real__bash || echo "exit $?")"

		if [[ "${REAL_ROOT:-}" == "" ]]; then
			echo "$0: unable to discover \$HOME value. Use -r ROOT option." >&2
			exit 1
		fi
	fi

	: ${REAL_HM_DIR:=$REAL_ROOT/.hm}
	: ${REAL_INDEX:=$REAL_HM_DIR/index}
	: ${REAL_FILES_DIR:=$REAL_HM_DIR/files}
	: ${REAL_BACKUP_ROOT_DIR:=$REAL_HM_DIR/backup/root/$(date +%Y%m%d-%H%M%S)}
	: ${REAL_BACKUP_FILES_DIR:=$REAL_HM_DIR/backup/files/$(date +%Y%m%d-%H%M%S)}
}
